"""Extract popup tokens from themes.css. Run --check to verify the committed output."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = set("font-sans font-mono bg-page bg-surface bg-surface-alt bg-elevated bg-input bg-strong text text-strong text-muted border border-input border-strong accent-border link link-hover focus-ring shadow-sm danger-text warning-bg warning-text warning-border success-bg success-text success-border info-bg info-text info-border".split())

def generate():
    source = (ROOT / "themes.css").read_text(encoding="utf-8")
    blocks = re.findall(r"([^{}]+)\{([^{}]+)\}", re.sub(r"/\*.*?\*/", "", source, flags=re.S))
    result = ["/* Generated by tools/generate-themes.py from themes.css. Do not edit. */"]
    copy_rules = []
    profiles = set()
    shared = {}
    for selector, body in blocks:
        values = dict(re.findall(r"(--[\w-]+|color-scheme)\s*:\s*([^;]+)(?:;|$)", body.strip()))
        if "--bg-page" not in values:
            shared.update(values)
            result.append(":root {\n" + "\n".join(f"  {k}: {v};" for k, v in values.items() if k in {"--font-sans", "--font-mono"}) + "\n}")
            continue
        family_match = re.search(r"data-site-theme=([\w-]+)", selector)
        family = family_match.group(1) if family_match else "classic"
        scheme = "dark" if "data-bs-theme=dark" in selector else "light"
        contrast = "more" if "data-contrast=high" in selector else "normal"
        profile = (family, scheme, contrast)
        if profile in profiles:
            raise ValueError("Duplicate palette: " + str(profile))
        profiles.add(profile)
        available = {**shared, **values}
        wanted = {"--" + token for token in TOKENS} & available.keys()
        pending = list(wanted)
        while pending:
            for dep in re.findall(r"var\((--[\w-]+)", available[pending.pop()]):
                if dep not in available:
                    raise ValueError("Missing dependency: " + dep)
                if dep not in wanted:
                    wanted.add(dep)
                    pending.append(dep)
        selector = f":root[data-theme-group=ts][data-site-theme={family}][data-bs-theme={scheme}][data-contrast={contrast}]"
        if profile == ("classic", "light", "normal"):
            selector = ":root, " + selector
        elif profile == ("classic", "dark", "normal"):
            selector = ":root[data-bs-theme=dark], " + selector
        result.append(selector + " {\n" + f"  color-scheme: {scheme};\n" + "\n".join(f"  {k}: {v};" for k, v in available.items() if k in wanted) + "\n}")
        roles = {"bg": "bg-strong", "text": "text-strong", "hover-bg": "bg-surface-alt", "hover-text": "text", "focus": "link", "border": "border-strong"}
        def literal(key):
            return re.sub(r"var\((--[\w-]+)\)", lambda m: literal(m.group(1)), available[key])
        copy_rules.append(f":root[data-theme-group=rating][data-copy-ts-theme={family}][data-copy-ts-scheme={scheme}][data-copy-ts-contrast={contrast}] {{\n" +
                          "\n".join(f"  --copy-ts-{role}: {literal('--' + token)};" for role, token in roles.items()) + "\n}")
    expected = {(f, s, c) for f in ("classic", "oldschool", "catppuccin", "colorblind") for s in ("light", "dark") for c in ("normal", "more")}
    if profiles != expected:
        raise ValueError("Expected four families × two modes × two contrast levels")
    result.extend(copy_rules)
    return "\n\n".join(result) + "\n"

output = ROOT / "src" / "popup-themes.css"
text = generate()
if "--check" in sys.argv:
    if not output.exists() or output.read_text(encoding="utf-8") != text:
        raise SystemExit("Run python tools/generate-themes.py to update popup-themes.css")
else:
    output.write_text(text, encoding="utf-8")
