"""Extract popup tokens from themes.css. Run --check to verify the committed output."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = set("font-sans font-mono bg-page bg-surface bg-surface-alt bg-elevated bg-input bg-strong text text-strong text-muted border border-input border-strong accent-border link link-hover focus-ring shadow-sm danger-text warning-bg warning-text warning-border success-bg success-text success-border info-bg info-text info-border".split())

def generate():
    source = (ROOT / "themes.css").read_text(encoding="utf-8")
    blocks = re.findall(r"([^{}]+)\{([^{}]+)\}", re.sub(r"/\*.*?\*/", "", source, flags=re.S))
    result = ["/* Generated by tools/generate-themes.py from themes.css. Do not edit. */"]
    copy_rules = []
    for selector, body in blocks:
        values = dict(re.findall(r"(--[\w-]+|color-scheme)\s*:\s*([^;]+);", body))
        if "--bg-strong" in values:
            family_match = re.search(r"data-site-theme=([\w-]+)", selector)
            family = family_match.group(1) if family_match else "classic"
            scheme = "dark" if "data-bs-theme=dark" in selector else "light"
            roles = {"bg": "bg-strong", "text": "text-strong", "hover-bg": "bg-surface-alt", "hover-text": "text", "focus": "link", "border": "border-strong"}
            copy_rules.append(f":root[data-theme-group=rating][data-copy-ts-theme={family}][data-copy-ts-scheme={scheme}] {{\n" +
                              "\n".join(f"  --copy-ts-{role}: {values['--' + token]};" for role, token in roles.items()) + "\n}")
        wanted = {"--" + token for token in TOKENS} & values.keys()
        if not wanted:
            continue
        # Include dependencies if an updated upstream palette uses var().
        pending = list(wanted)
        while pending:
            for dep in re.findall(r"var\((--[\w-]+)", values[pending.pop()]):
                if dep not in values:
                    raise ValueError("Missing token dependency: " + dep)
                if dep not in wanted:
                    wanted.add(dep)
                    pending.append(dep)
        if "color-scheme" in values:
            wanted.add("color-scheme")
        selector = selector.strip().replace(":root[data-site-theme=", ":root[data-theme-group=ts][data-site-theme=")
        result.append(selector + " {\n" + "\n".join("  " + key + ": " + value + ";" for key, value in values.items() if key in wanted) + "\n}")
    if len(result) != 8:
        raise ValueError("Expected shared font tokens and six TS palettes; review selectors when updating themes.css")
    result.extend(copy_rules)
    return "\n\n".join(result) + "\n"

output = ROOT / "src" / "popup-themes.css"
text = generate()
if "--check" in sys.argv:
    if not output.exists() or output.read_text(encoding="utf-8") != text:
        raise SystemExit("Run python tools/generate-themes.py to update popup-themes.css")
else:
    output.write_text(text, encoding="utf-8")
